$gwx_XC_16=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_16 || [];
function gz$gwx_XC_16_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_16_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_16_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_16_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'content data-v-7253af41'])
Z([3,'main-title data-v-7253af41'])
Z([3,'欢迎您在“浙商财险健康碳普惠平台”注册'])
Z([3,'par-header data-v-7253af41'])
Z([3,'data-v-7253af41'])
Z([3,'1. 服务内容'])
Z([3,'sec-header data-v-7253af41'])
Z([3,'服务的具体内容由浙商财险健康碳普惠平台根据实际情况提供。浙江财险健康碳普惠平台保留随时变更、中断或终止部分或全部网络服务的权利。'])
Z(z[3])
Z(z[4])
Z([3,'2. 账号登录'])
Z(z[6])
Z([3,'经过您的授权同意，您可使用微信账号登录本软件。'])
Z(z[3])
Z(z[4])
Z([3,'3. 使用规则'])
Z(z[6])
Z([3,'用户在浙商财险健康碳普惠平台注册登录后，必须遵循以下原则：'])
Z([3,'sec-content data-v-7253af41'])
Z(z[4])
Z([3,'(a) 遵守中国有关的法律和法规；'])
Z(z[4])
Z([3,'(b) 不得为任何非法目的而使用网络服务系统；'])
Z(z[4])
Z([3,'(c) 遵守所有与网络服务有关的网络协议、规定和程序；'])
Z(z[4])
Z([3,'(d) 不得利用浙江政务服务网进行任何可能对互联网的正常运转造成不利影响的行为；'])
Z(z[4])
Z([3,'(e) 不得利用浙商财险健康碳普惠平台传输任何骚扰性的、中伤他人的、辱骂性的、恐吓性的、庸俗淫秽的或其他任何非法的信息资料；'])
Z(z[4])
Z([3,'(f) 如发现任何非法使用用户帐号或帐号出现安全漏洞的情况，应立即通知浙商财险碳普惠小程序。'])
Z(z[3])
Z(z[4])
Z([3,'4. 内容所有权'])
Z(z[6])
Z([3,'4.1 浙商财险健康碳普惠平台提供的网络服务内容可能包括：文字、软件、声音、图片、录象、图表等。所有这些内容受版权、商标和其它财产所有权法律的保护。'])
Z(z[6])
Z([3,'4.2 用户只有在获得浙商财险健康碳普惠平台或其他相关权利人的授权之后才能使用这些内容，而不能擅自复制、再造这些内容、或创造与内容有关的派生产品。'])
Z(z[3])
Z(z[4])
Z([3,'5. 隐私保护'])
Z(z[6])
Z([3,'5.1 保护用户隐私是浙商财险健康碳普惠平台的一项基本政策，浙商财险健康碳普惠平台保证不对外公开或向第三方提供用户信息及用户在使用网络服务时存储在浙商财险健康碳普惠平台的非公开内容，但下列情况除外：'])
Z(z[18])
Z(z[4])
Z([3,'(a) 事先获得用户的明确授权；'])
Z(z[4])
Z([3,'(b) 根据有关的法律法规要求；'])
Z(z[4])
Z([3,'(c) 按照相关政府主管部门的要求；'])
Z(z[4])
Z([3,'(d) 为维护社会公众的利益；'])
Z(z[4])
Z([3,'(e) 为维护浙商保险健康碳普惠平台的合法权益。'])
Z(z[3])
Z(z[4])
Z([3,'6. 免责声明'])
Z(z[6])
Z([3,'6.1 用户明确同意其使用浙商保险健康碳普惠平台网络服务所存在的风险将完全由其自己承担；因其使用浙商保险健康碳普惠平台网络服务而产生的一切后果也由其自己承担，浙商保险碳普惠平台对用户不承担任何责任。'])
Z(z[6])
Z([3,'6.2 浙商保险碳普惠平台不担保网络服务一定能满足用户的要求，也不担保网络服务不会中断，对网络服务的及时性、安全性、准确性也都不作担保。'])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_16_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_16_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_16=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_16=true;
var x=['./pages/login/agreement/index.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_16_1()
var oFR=_n('view')
_rz(z,oFR,'class',0,e,s,gg)
var xGR=_n('view')
_rz(z,xGR,'class',1,e,s,gg)
var oHR=_oz(z,2,e,s,gg)
_(xGR,oHR)
_(oFR,xGR)
var fIR=_n('view')
_rz(z,fIR,'class',3,e,s,gg)
var cJR=_n('view')
_rz(z,cJR,'class',4,e,s,gg)
var hKR=_oz(z,5,e,s,gg)
_(cJR,hKR)
_(fIR,cJR)
var oLR=_n('view')
_rz(z,oLR,'class',6,e,s,gg)
var cMR=_oz(z,7,e,s,gg)
_(oLR,cMR)
_(fIR,oLR)
_(oFR,fIR)
var oNR=_n('view')
_rz(z,oNR,'class',8,e,s,gg)
var lOR=_n('view')
_rz(z,lOR,'class',9,e,s,gg)
var aPR=_oz(z,10,e,s,gg)
_(lOR,aPR)
_(oNR,lOR)
var tQR=_n('view')
_rz(z,tQR,'class',11,e,s,gg)
var eRR=_oz(z,12,e,s,gg)
_(tQR,eRR)
_(oNR,tQR)
_(oFR,oNR)
var bSR=_n('view')
_rz(z,bSR,'class',13,e,s,gg)
var oTR=_n('view')
_rz(z,oTR,'class',14,e,s,gg)
var xUR=_oz(z,15,e,s,gg)
_(oTR,xUR)
_(bSR,oTR)
var oVR=_n('view')
_rz(z,oVR,'class',16,e,s,gg)
var fWR=_oz(z,17,e,s,gg)
_(oVR,fWR)
_(bSR,oVR)
var cXR=_n('view')
_rz(z,cXR,'class',18,e,s,gg)
var hYR=_n('view')
_rz(z,hYR,'class',19,e,s,gg)
var oZR=_oz(z,20,e,s,gg)
_(hYR,oZR)
_(cXR,hYR)
var c1R=_n('view')
_rz(z,c1R,'class',21,e,s,gg)
var o2R=_oz(z,22,e,s,gg)
_(c1R,o2R)
_(cXR,c1R)
var l3R=_n('view')
_rz(z,l3R,'class',23,e,s,gg)
var a4R=_oz(z,24,e,s,gg)
_(l3R,a4R)
_(cXR,l3R)
var t5R=_n('view')
_rz(z,t5R,'class',25,e,s,gg)
var e6R=_oz(z,26,e,s,gg)
_(t5R,e6R)
_(cXR,t5R)
var b7R=_n('view')
_rz(z,b7R,'class',27,e,s,gg)
var o8R=_oz(z,28,e,s,gg)
_(b7R,o8R)
_(cXR,b7R)
var x9R=_n('view')
_rz(z,x9R,'class',29,e,s,gg)
var o0R=_oz(z,30,e,s,gg)
_(x9R,o0R)
_(cXR,x9R)
_(bSR,cXR)
_(oFR,bSR)
var fAS=_n('view')
_rz(z,fAS,'class',31,e,s,gg)
var cBS=_n('view')
_rz(z,cBS,'class',32,e,s,gg)
var hCS=_oz(z,33,e,s,gg)
_(cBS,hCS)
_(fAS,cBS)
var oDS=_n('view')
_rz(z,oDS,'class',34,e,s,gg)
var cES=_oz(z,35,e,s,gg)
_(oDS,cES)
_(fAS,oDS)
var oFS=_n('view')
_rz(z,oFS,'class',36,e,s,gg)
var lGS=_oz(z,37,e,s,gg)
_(oFS,lGS)
_(fAS,oFS)
_(oFR,fAS)
var aHS=_n('view')
_rz(z,aHS,'class',38,e,s,gg)
var tIS=_n('view')
_rz(z,tIS,'class',39,e,s,gg)
var eJS=_oz(z,40,e,s,gg)
_(tIS,eJS)
_(aHS,tIS)
var bKS=_n('view')
_rz(z,bKS,'class',41,e,s,gg)
var oLS=_oz(z,42,e,s,gg)
_(bKS,oLS)
_(aHS,bKS)
var xMS=_n('view')
_rz(z,xMS,'class',43,e,s,gg)
var oNS=_n('view')
_rz(z,oNS,'class',44,e,s,gg)
var fOS=_oz(z,45,e,s,gg)
_(oNS,fOS)
_(xMS,oNS)
var cPS=_n('view')
_rz(z,cPS,'class',46,e,s,gg)
var hQS=_oz(z,47,e,s,gg)
_(cPS,hQS)
_(xMS,cPS)
var oRS=_n('view')
_rz(z,oRS,'class',48,e,s,gg)
var cSS=_oz(z,49,e,s,gg)
_(oRS,cSS)
_(xMS,oRS)
var oTS=_n('view')
_rz(z,oTS,'class',50,e,s,gg)
var lUS=_oz(z,51,e,s,gg)
_(oTS,lUS)
_(xMS,oTS)
var aVS=_n('view')
_rz(z,aVS,'class',52,e,s,gg)
var tWS=_oz(z,53,e,s,gg)
_(aVS,tWS)
_(xMS,aVS)
_(aHS,xMS)
_(oFR,aHS)
var eXS=_n('view')
_rz(z,eXS,'class',54,e,s,gg)
var bYS=_n('view')
_rz(z,bYS,'class',55,e,s,gg)
var oZS=_oz(z,56,e,s,gg)
_(bYS,oZS)
_(eXS,bYS)
var x1S=_n('view')
_rz(z,x1S,'class',57,e,s,gg)
var o2S=_oz(z,58,e,s,gg)
_(x1S,o2S)
_(eXS,x1S)
var f3S=_n('view')
_rz(z,f3S,'class',59,e,s,gg)
var c4S=_oz(z,60,e,s,gg)
_(f3S,c4S)
_(eXS,f3S)
_(oFR,eXS)
_(r,oFR)
return r
}
e_[x[0]]=e_[x[0]]||{f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_16";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_16();
	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/login/agreement/index.wxml'] = [$gwx_XC_16, './pages/login/agreement/index.wxml'];else __wxAppCode__['pages/login/agreement/index.wxml'] = $gwx_XC_16( './pages/login/agreement/index.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/login/agreement/index.wxss'] = setCssToHead([".",[1],"content.",[1],"data-v-7253af41{color:#121212;font-family:PingFang SC;font-size:12px;font-style:normal;font-weight:500;height:",[0,1408],";left:",[0,64],";line-height:22px;position:absolute;width:",[0,622],"}\n.",[1],"content .",[1],"main-title.",[1],"data-v-7253af41{font-size:",[0,26],";font-weight:700;text-align:center}\n.",[1],"content .",[1],"par-header.",[1],"data-v-7253af41{font-weight:700;margin-top:",[0,20],"}\n.",[1],"content .",[1],"par-header .",[1],"sec-header.",[1],"data-v-7253af41{font-weight:400;margin-top:",[0,20],";text-indent:",[0,26],"}\n.",[1],"content .",[1],"par-header .",[1],"sec-content.",[1],"data-v-7253af41{font-weight:400;text-indent:",[0,52],"}\n.",[1],"timedate.",[1],"data-v-7253af41{align-items:center;display:flex;flex-direction:column;height:",[0,119],";justify-content:center;position:absolute;top:",[0,-210],";width:100%}\n.",[1],"jiange.",[1],"data-v-7253af41{height:",[0,40],"}\n",],undefined,{path:"./pages/login/agreement/index.wxss"});
}