$gwx_XC_11=function(_,_v,_n,_p,_s,_wp,_wl,$gwn,$gwl,$gwh,wh,$gstack,$gwrt,gra,grb,TestTest,wfor,_ca,_da,_r,_rz,_o,_oz,_1,_1z,_2,_2z,_m,_mz,nv_getDate,nv_getRegExp,nv_console,nv_parseInt,nv_parseFloat,nv_isNaN,nv_isFinite,nv_decodeURI,nv_decodeURIComponent,nv_encodeURI,nv_encodeURIComponent,$gdc,nv_JSON,_af,_gv,_ai,_grp,_gd,_gapi,$ixc,_ic,_w,_ev,_tsd){return function(path,global){
if(typeof global==='undefined'){if (typeof __GWX_GLOBAL__==='undefined')global={};else global=__GWX_GLOBAL__;}if(typeof __WXML_GLOBAL__ === 'undefined') {__WXML_GLOBAL__={};
}__WXML_GLOBAL__.modules = __WXML_GLOBAL__.modules || {};
var e_={}
if(typeof(global.entrys)==='undefined')global.entrys={};e_=global.entrys;
var d_={}
if(typeof(global.defines)==='undefined')global.defines={};d_=global.defines;
var f_={}
if(typeof(global.modules)==='undefined')global.modules={};f_=global.modules || {};
var p_={}
__WXML_GLOBAL__.ops_cached = __WXML_GLOBAL__.ops_cached || {}
__WXML_GLOBAL__.ops_set = __WXML_GLOBAL__.ops_set || {};
__WXML_GLOBAL__.ops_init = __WXML_GLOBAL__.ops_init || {};
var z=__WXML_GLOBAL__.ops_set.$gwx_XC_11 || [];
function gz$gwx_XC_11_1(){
if( __WXML_GLOBAL__.ops_cached.$gwx_XC_11_1)return __WXML_GLOBAL__.ops_cached.$gwx_XC_11_1
__WXML_GLOBAL__.ops_cached.$gwx_XC_11_1=[];
(function(z){var a=11;function Z(ops){z.push(ops)}
Z([3,'detail-contain data-v-6d82ae52'])
Z([3,'data-v-6d82ae52'])
Z([[2,'+'],[[2,'+'],[[2,'+'],[1,'height:'],[[2,'+'],[[6],[[7],[3,'menuInfo']],[3,'bottom']],[1,'px']]],[1,';']],[[2,'+'],[[2,'+'],[1,'background-color:'],[1,'transparent']],[1,';']]])
Z(z[1])
Z([[2,'+'],[[2,'+'],[1,'height:'],[[2,'+'],[[6],[[7],[3,'menuInfo']],[3,'top']],[1,'px']]],[1,';']])
Z(z[1])
Z([[2,'+'],[[2,'+'],[1,'height:'],[[2,'+'],[[6],[[7],[3,'systemInfo']],[3,'statusBarHeight']],[1,'px']]],[1,';']])
Z([3,'nav-title data-v-6d82ae52'])
Z([[2,'+'],[[2,'+'],[[2,'+'],[1,'height:'],[[2,'+'],[[2,'-'],[[6],[[7],[3,'menuInfo']],[3,'bottom']],[[6],[[7],[3,'systemInfo']],[3,'statusBarHeight']]],[1,'px']]],[1,';']],[[2,'+'],[[2,'+'],[1,'line-height:'],[[2,'+'],[[2,'-'],[[6],[[7],[3,'menuInfo']],[3,'bottom']],[[6],[[7],[3,'systemInfo']],[3,'statusBarHeight']]],[1,'px']]],[1,';']]])
Z([3,'record-accout data-v-6d82ae52'])
Z([3,'订单详情'])
Z([3,'__e'])
Z(z[1])
Z([[4],[[5],[[4],[[5],[[5],[1,'tap']],[[4],[[5],[[4],[[5],[[5],[1,'goRecord']],[[4],[[5],[1,'$event']]]]]]]]]]])
Z([3,'height:100%;width:98rpx;'])
Z([3,'left-home data-v-6d82ae52'])
Z([a,[3,'background:url(\x27'],[[7],[3,'imgUrl']],[3,'/static/icons/grey-row.png\x27);background-position:top;background-repeat:no-repeat;background-size:contain;']])
Z([3,'detail-bg data-v-6d82ae52'])
Z([a,z[16][1],z[16][2],[3,'/static/carbon/green-bg.svg\x27);background-position:top;background-repeat:no-repeat;background-size:cover;']])
Z([3,'detail-success data-v-6d82ae52'])
Z([a,z[16][1],z[16][2],[3,'/static/carbon/title-success.svg\x27);background-position:top;background-repeat:no-repeat;background-size:cover;']])
Z([3,'detail-item data-v-6d82ae52'])
Z([3,'item data-v-6d82ae52'])
Z([3,'item-image data-v-6d82ae52'])
Z([a,z[16][1],z[16][2],[3,'/sysFileInfo/previewByObjectName?fileBucket\x3ddefaultBucket\x26fileObjectName\x3d'],[[6],[[7],[3,'goodInfo']],[3,'goodsIcon']],[3,'\x27);background-position:top;background-repeat:no-repeat;background-size:cover;']])
Z([3,'item-desc data-v-6d82ae52'])
Z([3,'item-title data-v-6d82ae52'])
Z([a,[[2,'+'],[[2,'+'],[1,''],[[6],[[7],[3,'goodInfo']],[3,'goodsName']]],[1,'']]])
Z([3,'item-jifen data-v-6d82ae52'])
Z([a,[[2,'+'],[[2,'+'],[1,'积分数：'],[[6],[[7],[3,'goodInfo']],[3,'spend']]],[1,'']]])
Z([3,'item-count data-v-6d82ae52'])
Z([a,[[2,'+'],[[2,'+'],[1,'x '],[[6],[[7],[3,'goodInfo']],[3,'count']]],[1,'']]])
Z([3,'info data-v-6d82ae52'])
Z([3,'user-title data-v-6d82ae52'])
Z([3,'兑换信息'])
Z([3,'info-item data-v-6d82ae52'])
Z([3,'title data-v-6d82ae52'])
Z([3,'积分消耗'])
Z(z[1])
Z([a,[[6],[[7],[3,'goodInfo']],[3,'spend']]])
Z(z[35])
Z(z[36])
Z([3,'兑换时间'])
Z(z[1])
Z([a,[[6],[[7],[3,'goodInfo']],[3,'createTime']]])
Z(z[35])
Z(z[36])
Z([3,'订单编号'])
Z(z[1])
Z([a,[[6],[[7],[3,'goodInfo']],[3,'id']]])
Z([3,'user data-v-6d82ae52'])
Z(z[33])
Z([3,'收货人信息'])
Z(z[35])
Z(z[36])
Z([3,'收货人'])
Z(z[1])
Z([a,[[6],[[7],[3,'goodInfo']],[3,'receiverName']]])
Z(z[35])
Z(z[36])
Z([3,'手机号码'])
Z(z[1])
Z([a,[[6],[[7],[3,'goodInfo']],[3,'receiverPhone']]])
Z(z[35])
Z(z[36])
Z([3,'收货地址'])
Z([3,'address data-v-6d82ae52'])
Z([a,[[6],[[7],[3,'goodInfo']],[3,'receiverAddress']]])
})(__WXML_GLOBAL__.ops_cached.$gwx_XC_11_1);return __WXML_GLOBAL__.ops_cached.$gwx_XC_11_1
}
__WXML_GLOBAL__.ops_set.$gwx_XC_11=z;
__WXML_GLOBAL__.ops_init.$gwx_XC_11=true;
var x=['./pages/health/selfpage/detail.wxml'];d_[x[0]]={}
var m0=function(e,s,r,gg){
var z=gz$gwx_XC_11_1()
var cZI=_n('view')
_rz(z,cZI,'class',0,e,s,gg)
var h1I=_mz(z,'view',['class',1,'style',1],[],e,s,gg)
var o2I=_mz(z,'view',['class',3,'style',1],[],e,s,gg)
var c3I=_mz(z,'view',['class',5,'style',1],[],e,s,gg)
_(o2I,c3I)
_(h1I,o2I)
var o4I=_mz(z,'view',['class',7,'style',1],[],e,s,gg)
var l5I=_n('view')
_rz(z,l5I,'class',9,e,s,gg)
var a6I=_oz(z,10,e,s,gg)
_(l5I,a6I)
_(o4I,l5I)
var t7I=_mz(z,'view',['bindtap',11,'class',1,'data-event-opts',2,'style',3],[],e,s,gg)
var e8I=_mz(z,'view',['class',15,'style',1],[],e,s,gg)
_(t7I,e8I)
_(o4I,t7I)
_(h1I,o4I)
_(cZI,h1I)
var b9I=_mz(z,'view',['class',17,'style',1],[],e,s,gg)
var o0I=_mz(z,'view',['class',19,'style',1],[],e,s,gg)
_(b9I,o0I)
_(cZI,b9I)
var xAJ=_n('view')
_rz(z,xAJ,'class',21,e,s,gg)
var oBJ=_n('view')
_rz(z,oBJ,'class',22,e,s,gg)
var fCJ=_mz(z,'view',['class',23,'style',1],[],e,s,gg)
_(oBJ,fCJ)
var cDJ=_n('view')
_rz(z,cDJ,'class',25,e,s,gg)
var hEJ=_n('view')
_rz(z,hEJ,'class',26,e,s,gg)
var oFJ=_oz(z,27,e,s,gg)
_(hEJ,oFJ)
_(cDJ,hEJ)
var cGJ=_n('view')
_rz(z,cGJ,'class',28,e,s,gg)
var oHJ=_oz(z,29,e,s,gg)
_(cGJ,oHJ)
_(cDJ,cGJ)
var lIJ=_n('view')
_rz(z,lIJ,'class',30,e,s,gg)
var aJJ=_oz(z,31,e,s,gg)
_(lIJ,aJJ)
_(cDJ,lIJ)
_(oBJ,cDJ)
_(xAJ,oBJ)
var tKJ=_n('view')
_rz(z,tKJ,'class',32,e,s,gg)
var eLJ=_n('view')
_rz(z,eLJ,'class',33,e,s,gg)
var bMJ=_oz(z,34,e,s,gg)
_(eLJ,bMJ)
_(tKJ,eLJ)
var oNJ=_n('view')
_rz(z,oNJ,'class',35,e,s,gg)
var xOJ=_n('view')
_rz(z,xOJ,'class',36,e,s,gg)
var oPJ=_oz(z,37,e,s,gg)
_(xOJ,oPJ)
_(oNJ,xOJ)
var fQJ=_n('view')
_rz(z,fQJ,'class',38,e,s,gg)
var cRJ=_oz(z,39,e,s,gg)
_(fQJ,cRJ)
_(oNJ,fQJ)
_(tKJ,oNJ)
var hSJ=_n('view')
_rz(z,hSJ,'class',40,e,s,gg)
var oTJ=_n('view')
_rz(z,oTJ,'class',41,e,s,gg)
var cUJ=_oz(z,42,e,s,gg)
_(oTJ,cUJ)
_(hSJ,oTJ)
var oVJ=_n('view')
_rz(z,oVJ,'class',43,e,s,gg)
var lWJ=_oz(z,44,e,s,gg)
_(oVJ,lWJ)
_(hSJ,oVJ)
_(tKJ,hSJ)
var aXJ=_n('view')
_rz(z,aXJ,'class',45,e,s,gg)
var tYJ=_n('view')
_rz(z,tYJ,'class',46,e,s,gg)
var eZJ=_oz(z,47,e,s,gg)
_(tYJ,eZJ)
_(aXJ,tYJ)
var b1J=_n('view')
_rz(z,b1J,'class',48,e,s,gg)
var o2J=_oz(z,49,e,s,gg)
_(b1J,o2J)
_(aXJ,b1J)
_(tKJ,aXJ)
_(xAJ,tKJ)
var x3J=_n('view')
_rz(z,x3J,'class',50,e,s,gg)
var o4J=_n('view')
_rz(z,o4J,'class',51,e,s,gg)
var f5J=_oz(z,52,e,s,gg)
_(o4J,f5J)
_(x3J,o4J)
var c6J=_n('view')
_rz(z,c6J,'class',53,e,s,gg)
var h7J=_n('view')
_rz(z,h7J,'class',54,e,s,gg)
var o8J=_oz(z,55,e,s,gg)
_(h7J,o8J)
_(c6J,h7J)
var c9J=_n('view')
_rz(z,c9J,'class',56,e,s,gg)
var o0J=_oz(z,57,e,s,gg)
_(c9J,o0J)
_(c6J,c9J)
_(x3J,c6J)
var lAK=_n('view')
_rz(z,lAK,'class',58,e,s,gg)
var aBK=_n('view')
_rz(z,aBK,'class',59,e,s,gg)
var tCK=_oz(z,60,e,s,gg)
_(aBK,tCK)
_(lAK,aBK)
var eDK=_n('view')
_rz(z,eDK,'class',61,e,s,gg)
var bEK=_oz(z,62,e,s,gg)
_(eDK,bEK)
_(lAK,eDK)
_(x3J,lAK)
var oFK=_n('view')
_rz(z,oFK,'class',63,e,s,gg)
var xGK=_n('view')
_rz(z,xGK,'class',64,e,s,gg)
var oHK=_oz(z,65,e,s,gg)
_(xGK,oHK)
_(oFK,xGK)
var fIK=_n('view')
_rz(z,fIK,'class',66,e,s,gg)
var cJK=_oz(z,67,e,s,gg)
_(fIK,cJK)
_(oFK,fIK)
_(x3J,oFK)
_(xAJ,x3J)
_(cZI,xAJ)
_(r,cZI)
return r
}
e_[x[0]]=e_[x[0]]||{f:m0,j:[],i:[],ti:[],ic:[]}
if(path&&e_[path]){
outerGlobal.__wxml_comp_version__=0.02
return function(env,dd,global){$gwxc=0;var root={"tag":"wx-page"};root.children=[]
;g="$gwx_XC_11";var main=e_[path].f
if (typeof global==="undefined")global={};global.f=$gdc(f_[path],"",1);
if(typeof(outerGlobal.__webview_engine_version__)!='undefined'&&outerGlobal.__webview_engine_version__+1e-6>=0.02+1e-6&&outerGlobal.__mergeData__)
{
env=outerGlobal.__mergeData__(env,dd);
}
try{
main(env,{},root,global);
_tsd(root)
if(typeof(outerGlobal.__webview_engine_version__)=='undefined'|| outerGlobal.__webview_engine_version__+1e-6<0.01+1e-6){return _ev(root);}
}catch(err){
console.log(err)
}
;g="";
return root;
}
}
}
}(__g.a,__g.b,__g.c,__g.d,__g.e,__g.f,__g.g,__g.h,__g.i,__g.j,__g.k,__g.l,__g.m,__g.n,__g.o,__g.p,__g.q,__g.r,__g.s,__g.t,__g.u,__g.v,__g.w,__g.x,__g.y,__g.z,__g.A,__g.B,__g.C,__g.D,__g.E,__g.F,__g.G,__g.H,__g.I,__g.J,__g.K,__g.L,__g.M,__g.N,__g.O,__g.P,__g.Q,__g.R,__g.S,__g.T,__g.U,__g.V,__g.W,__g.X,__g.Y,__g.Z,__g.aa);if(__vd_version_info__.delayedGwx||false)$gwx_XC_11();
	if (__vd_version_info__.delayedGwx) __wxAppCode__['pages/health/selfpage/detail.wxml'] = [$gwx_XC_11, './pages/health/selfpage/detail.wxml'];else __wxAppCode__['pages/health/selfpage/detail.wxml'] = $gwx_XC_11( './pages/health/selfpage/detail.wxml' );
	
var noCss=typeof __vd_version_info__!=='undefined'&&__vd_version_info__.noCss===true;if(!noCss){__wxAppCode__['pages/health/selfpage/detail.wxss'] = setCssToHead([".",[1],"detail-contain.",[1],"data-v-6d82ae52{background:#f6f6f6;display:flex;flex-direction:column;min-height:100vh;position:relative}\n.",[1],"nav-title.",[1],"data-v-6d82ae52{color:#000;font-size:",[0,32],";font-weight:450;position:relative;text-align:center;z-index:3}\n.",[1],"nav-title .",[1],"left-home.",[1],"data-v-6d82ae52{bottom:0;height:",[0,28],";left:",[0,20],";margin:auto 0;position:absolute;top:0;width:",[0,28],"}\n.",[1],"nav-title .",[1],"record-accout.",[1],"data-v-6d82ae52{color:#000;font-weight:700;height:100%;position:absolute;right:0;top:0;width:100%;z-index:-1}\n.",[1],"detail-bg.",[1],"data-v-6d82ae52{height:",[0,416],";position:absolute;top:",[0,-1],";width:100%}\n.",[1],"detail-bg .",[1],"detail-success.",[1],"data-v-6d82ae52{bottom:0;height:",[0,72],";left:0;margin:auto;position:absolute;right:0;top:0;width:",[0,284],"}\n.",[1],"detail-item.",[1],"data-v-6d82ae52{position:absolute;top:",[0,280],";width:100%}\n.",[1],"detail-item .",[1],"item.",[1],"data-v-6d82ae52{background:#fff;border-radius:",[0,25],";display:flex;height:",[0,168],";margin:0 auto;padding:",[0,20],";width:",[0,646],"}\n.",[1],"detail-item .",[1],"item .",[1],"item-image.",[1],"data-v-6d82ae52{background:green;border-radius:25%;height:",[0,118],";margin-right:",[0,25],";width:",[0,118],"}\n.",[1],"detail-item .",[1],"item .",[1],"item-desc.",[1],"data-v-6d82ae52{display:flex;flex-direction:column;justify-content:flex-start}\n.",[1],"detail-item .",[1],"item .",[1],"item-desc .",[1],"item-title.",[1],"data-v-6d82ae52{font-size:14px;font-weight:700;margin-bottom:",[0,10],"}\n.",[1],"detail-item .",[1],"item .",[1],"item-desc .",[1],"item-jifen.",[1],"data-v-6d82ae52{color:grey;font-size:13px;margin-bottom:",[0,10],"}\n.",[1],"detail-item .",[1],"item .",[1],"item-desc .",[1],"item-count.",[1],"data-v-6d82ae52{color:grey;font-size:13px}\n.",[1],"detail-item .",[1],"info.",[1],"data-v-6d82ae52{background:#fff;border-radius:",[0,25],";display:flex;flex-direction:column;height:",[0,260],";justify-content:space-evenly;margin:",[0,10]," auto;padding:",[0,20],";width:",[0,646],"}\n.",[1],"detail-item .",[1],"info .",[1],"user-title.",[1],"data-v-6d82ae52{font-size:13px;font-weight:700;padding-left:",[0,10],";position:relative}\n.",[1],"detail-item .",[1],"info .",[1],"user-title.",[1],"data-v-6d82ae52::after{background:#71b54b;bottom:",[0,5],";clear:both;content:\x22\x22;display:block;height:15px;left:",[0,-5],";position:absolute;width:3px}\n.",[1],"detail-item .",[1],"info .",[1],"info-item.",[1],"data-v-6d82ae52{display:flex;justify-content:space-between}\n.",[1],"detail-item .",[1],"info .",[1],"info-item .",[1],"title.",[1],"data-v-6d82ae52{color:grey;font-size:13px}\n.",[1],"detail-item .",[1],"user.",[1],"data-v-6d82ae52{background:#fff;border-radius:",[0,25],";display:flex;flex-direction:column;height:",[0,300],";justify-content:space-evenly;margin:",[0,10]," auto;padding:",[0,20],";width:",[0,646],"}\n.",[1],"detail-item .",[1],"user .",[1],"user-title.",[1],"data-v-6d82ae52{font-size:13px;font-weight:700;padding-left:",[0,10],";position:relative}\n.",[1],"detail-item .",[1],"user .",[1],"user-title.",[1],"data-v-6d82ae52::after{background:#71b54b;bottom:",[0,5],";clear:both;content:\x22\x22;display:block;height:15px;left:",[0,-5],";position:absolute;width:3px}\n.",[1],"detail-item .",[1],"user .",[1],"info-item.",[1],"data-v-6d82ae52{display:flex;justify-content:space-between}\n.",[1],"detail-item .",[1],"user .",[1],"info-item .",[1],"title.",[1],"data-v-6d82ae52{color:grey;font-size:13px}\n.",[1],"detail-item .",[1],"user .",[1],"info-item .",[1],"address.",[1],"data-v-6d82ae52{text-align:right;width:",[0,420],"}\n",],undefined,{path:"./pages/health/selfpage/detail.wxss"});
}