name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }} # Optional; to run only when a label is attached
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ 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 }}
          OPENAI_API_KEY: ${{ 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 }}
          # Optional
          LANGUAGE: Chinese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL:
          top_p: 1
          temperature: 1
